dvrk_psm:
  PSM:
    rev_joint_controller:
      p: 200.0
      i: 0.0
      d: 10.0
    outer_yaw_joint_controller:
      p: 50.0
      i: 0.0
      d: 5.0
    outer_pitch_joint_1_controller:
      p: 50.0
      i: 0.0
      d: 5.0
    outer_insertion_joint_controller:
      p: 4000.0
      i: 0.0
      d: 100.0
    outer_roll_joint_controller:
      p: 1.0
      i: 0.002
      d: 0.1
    outer_wrist_pitch_joint_controller:
      p: 2.0
      i: 0.005
      d: 0.2
    outer_wrist_yaw_joint_controller:
      p: 2.0
      i: 0.005
      d: 0.2
    outer_wrist_open_angle_joint_1_controller:
      p: 10.0
      i: 0.1
      d: 1.0
    outer_wrist_open_angle_joint_2_controller:
      p: 10.0
      i: 0.1
      d: 1.0
